// Package export writes the resolved palette for other repositories to read.
//
// This is the whole of what basalt hands downstream. It does not know what a
// highlight group or a bar chip is and must not learn: which entry a role takes
// belongs to whoever owns the thing being themed.
package export

import (
	"encoding/json"
	"math"

	"github.com/azazeal/basalt/internal/oklch"
	"github.com/azazeal/basalt/internal/palette"
)

// note marks the file as generated, since JSON has no comments.
const note = "Generated by basalt from palette/basalt.toml. Do not edit: run" +
	" `.github/scripts/screenshot -s` instead. Surfaces are ordered deepest to" +
	" lightest and that order is meaningful."

// JSON renders the palette as the file downstream reads.
func JSON(p *palette.Palette) ([]byte, error) {
	d := document{
		Note:     note,
		Surfaces: make([]surface, len(p.Surfaces)),
		Accents:  make([]accent, len(p.Accents)),
	}

	for i, c := range p.Surfaces {
		d.Surfaces[i] = surface{Name: c.Name, Note: c.Note, color: colorOf(c.LCh)}
	}

	for i, a := range p.Accents {
		d.Accents[i] = accent{
			Name: a.Name,
			Note: a.Note,
			Why:  a.Why,
			Hue:  round(a.Hue, 1),

			Text:      colorOf(a.Text),
			Deep:      colorOf(a.Deep),
			Wash:      colorOf(a.Wash),
			Container: colorOf(a.Container),
		}
	}

	out, err := json.MarshalIndent(d, "", "  ")
	if err != nil {
		return nil, err
	}

	return append(out, '\n'), nil
}

type document struct {
	// The $ sets it apart from the entries' notes: this one is about the file.
	Note string `json:"$note"`

	// Arrays rather than objects: their order carries meaning and a JSON object
	// does not keep one.
	Surfaces []surface `json:"surfaces"`
	Accents  []accent  `json:"accents"`
}

type surface struct {
	Name string `json:"name"`
	Note string `json:"note"`

	color
}

// accent is one place on the wheel and the four renditions it resolves to.
type accent struct {
	Name string `json:"name"`
	Note string `json:"note"`

	// Why is present only on an accent off the common lightness, and says what
	// about sRGB or vision made it necessary.
	Why string `json:"why,omitempty"`

	Hue float64 `json:"hue"`

	Text      color `json:"text"`
	Deep      color `json:"deep"`
	Wash      color `json:"wash"`
	Container color `json:"container"`
}

// color is one value, as a hex and as the position it was computed from, so a
// consumer compositing or deriving a state need not undo the conversion first.
type color struct {
	Hex string `json:"hex"`

	Lightness float64 `json:"lightness"`
	Chroma    float64 `json:"chroma"`
	Hue       float64 `json:"hue"`
}

func colorOf(c oklch.LCh) color {
	return color{
		Hex:       c.Hex(),
		Lightness: round(c.L*100, 1),
		Chroma:    round(c.C, 4),
		Hue:       round(c.H, 1),
	}
}

// round keeps the file readable, and the same on machines whose floating point
// differs in the last bits.
func round(v float64, places int) float64 {
	p := math.Pow(10, float64(places))

	return math.Round(v*p) / p
}
