// Package export writes the resolved palette for other repositories to read.
//
// This is the whole of what basalt hands downstream. It does not know what a
// highlight group or a bar chip is and must not learn: which entry a role takes
// belongs to whoever owns the thing being themed.
package export

import (
	"encoding/json"
	"math"

	"github.com/azazeal/basalt/internal/palette"
)

// note rides at the top, since JSON has no comments and a generated file with
// no way to say so is one somebody edits by hand.
const note = "Generated by basalt from palette/basalt.toml. Do not edit: run" +
	" `go run ./cmd/basalt -json basalt.json` instead. Surfaces are ordered" +
	" deepest to lightest and that order is meaningful."

// Color is one value, as a hex and as the position it was computed from. The
// position saves a consumer compositing or deriving a state from having to undo
// the conversion first.
type Color struct {
	Hex string `json:"hex"`

	Lightness float64 `json:"lightness"`
	Chroma    float64 `json:"chroma"`
	Hue       float64 `json:"hue"`
}

// Surface is one step of the ladder.
type Surface struct {
	Name string `json:"name"`
	Note string `json:"note"`

	Color
}

// Accent is one place on the wheel and the four renditions it resolves to.
type Accent struct {
	Name string `json:"name"`
	Note string `json:"note"`

	// Why is present only on an accent off the common lightness, and says what
	// about sRGB or vision made it necessary.
	Why string `json:"why,omitempty"`

	Hue float64 `json:"hue"`

	// Text doubles as a bright fill, which is why four renditions cover five
	// uses.
	Text      Color `json:"text"`
	Deep      Color `json:"deep"`
	Wash      Color `json:"wash"`
	Container Color `json:"container"`
}

type document struct {
	// The sigil parts this from the notes on the entries below it. Those say
	// what a color is for and are the file's content; this one is about the
	// file itself.
	Note string `json:"$note"`

	// Arrays rather than objects: their order carries meaning and a JSON object
	// does not keep one. Neovim's decoder hands back a table, which has none.
	Surfaces []Surface `json:"surfaces"`
	Accents  []Accent  `json:"accents"`
}

// round keeps the file diffable: full float precision would make every
// regeneration look like a change nobody made.
func round(v float64, places int) float64 {
	p := math.Pow(10, float64(places))

	return math.Round(v*p) / p
}

func colorOf(c palette.Color) Color {
	return Color{
		Hex:       c.Hex(),
		Lightness: round(c.LCh.L*100, 1),
		Chroma:    round(c.LCh.C, 4),
		Hue:       round(c.LCh.H, 1),
	}
}

// JSON renders the palette as the file downstream reads.
func JSON(p *palette.Palette) ([]byte, error) {
	d := document{
		Note:     note,
		Surfaces: make([]Surface, len(p.Surfaces)),
		Accents:  make([]Accent, len(p.Accents)),
	}

	for i, c := range p.Surfaces {
		d.Surfaces[i] = Surface{Name: c.Name, Note: c.Note, Color: colorOf(c)}
	}

	for i, a := range p.Accents {
		d.Accents[i] = Accent{
			Name: a.Name,
			Note: a.Note,
			Why:  a.Why,
			Hue:  round(a.Hue, 1),

			Text:      colorOf(a.Text),
			Deep:      colorOf(a.Deep),
			Wash:      colorOf(a.Wash),
			Container: colorOf(a.Container),
		}
	}

	out, err := json.MarshalIndent(d, "", "  ")
	if err != nil {
		return nil, err
	}

	return append(out, '\n'), nil
}
